counter:
  step: 2
  initialValue: 4

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: passw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop